#Programa que exibe a tabuada de um número inteiro informado pelo usuário
num = int(input('Digite o número que deseja ver a tabuada: '))
print(f'{5 * "*="}TABUADA DE "{num}"{5 * "*="}')
print(f'{5 * "=>"} {num}  X  0  =  {num * 0} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  1  =  {num * 1} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  2  =  {num * 2} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  3  =  {num * 3} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  4  =  {num * 4} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  5  =  {num * 5} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  6  =  {num * 6} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  7  =  {num * 7} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  8  =  {num * 8} {5 * "<="}')
print(f'{5 * "=>"} {num}  X  9  =  {num * 9} {5 * "<="}')
print(f'{5 * "=>"} {num}  X 10  =  {num * 10} {5 * "<="}')
print(f'{4 * "*="}FIM   DA   TABUADA {4 * "*="}')
